spring.application.name=blog
server.port=8888

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.username=post_it
spring.datasource.password=1234

file.upload.path=C:/upload/

// google smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ug034516@gmail.com
spring.mail.password=ohdi hpup imiy ymdx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true